#!/usr/bin/env python
#
# This file is part of the optimadeapi project, which is covered by the MIT License
# Details are given in the LICENSE file in the root of this project.
# (c) Rickard Armiento, 2016-2017

import os, sys
import cgitb
cgitb.enable()
path=os.path.split(os.path.split(os.path.abspath(os.path.realpath(sys.argv[0])))[0])[0]+"/python"
sys.path.insert(1,path)
os.chdir(path)
import optimadeapi.query
