#!/usr/bin/env python
import os, sys
import cgitb
cgitb.enable()
path=os.path.split(os.path.split(os.path.abspath(os.path.realpath(sys.argv[0])))[0])[0]+"/python"
sys.path.insert(1,path)
import optimadeapi.query
